# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'AudioPoligono' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AudioPoligono
  pod 'EZAudio', '~> 1.1.4'

  target 'AudioPoligonoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AudioPoligonoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
